/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticationImport } from './routes/_authentication'
import { Route as IndexImport } from './routes/index'
import { Route as TodoListTodoListImport } from './routes/_todo-list/todo-list'
import { Route as AuthenticationProfileImport } from './routes/_authentication/profile'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationRoute = AuthenticationImport.update({
  id: '/_authentication',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TodoListTodoListRoute = TodoListTodoListImport.update({
  path: '/todo-list',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticationProfileRoute = AuthenticationProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthenticationRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authentication': {
      id: '/_authentication'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticationImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authentication/profile': {
      id: '/_authentication/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticationProfileImport
      parentRoute: typeof AuthenticationImport
    }
    '/_todo-list/todo-list': {
      id: '/_todo-list/todo-list'
      path: '/todo-list'
      fullPath: '/todo-list'
      preLoaderRoute: typeof TodoListTodoListImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticationRoute: AuthenticationRoute.addChildren({
    AuthenticationProfileRoute,
  }),
  LoginRoute,
  TodoListTodoListRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/",
        "/_authentication",
        "/login",
        "/_todo-list/todo-list"
      ]
    },
    "/": {
      "filePath": "index.jsx"
    },
    "/_authentication": {
      "filePath": "_authentication.jsx",
      "children": [
        "/_authentication/profile"
      ]
    },
    "/login": {
      "filePath": "login.jsx"
    },
    "/_authentication/profile": {
      "filePath": "_authentication/profile.jsx",
      "parent": "/_authentication"
    },
    "/_todo-list/todo-list": {
      "filePath": "_todo-list/todo-list.jsx"
    }
  }
}
ROUTE_MANIFEST_END */
